feat: v*タグに反応してmainブランチかどうか判断

diff --git a/.github/workflows/publish-to-test-pypi.yml b/.github/workflows/publish-to-test-pypi.yml
--- a/.github/workflows/publish-to-test-pypi.yml
+++ b/.github/workflows/publish-to-test-pypi.yml
@@ -6,13 +6,27 @@ on:
       - "v*"
 
 jobs:
-  build:
-    name: Build distribution
+  verify:
+    name: Verify tag is on main branch
     runs-on: ubuntu-latest
-
     steps:
       - name: Check out source
-        uses: actions/checkout@v6
+        uses: actions/checkout@v7
+        with:
+          fetch-depth: 0
+
+      - name: Verify tag is valid by git CLI
+        run: |
+          git fetch origin main
+          git merge-base --is-ancestor ${{ github.sha }} origin/main || (echo "Error: Tag is not on main branch" && exit 1)
+
+  build:
+    name: Build distribution package
+    needs: verify
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out source
+        uses: actions/checkout@v7
 
       - name: Install uv
         uses: astral-sh/setup-uv@v7
@@ -22,22 +36,21 @@ jobs:
       - name: Set up Python
         run: uv python install 3.14
 
-      - name: Build distribution
+      - name: Run uv build
         run: uv build
 
-      - name: Upload distribution artifact
+      - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: dist
           path: dist/*
 
-  publish:
+  publish-TestPyPI:
     name: Publish to TestPyPI
-    runs-on: ubuntu-latest
     needs: build
-
+    runs-on: ubuntu-latest
     steps:
-      - name: Download distribution artifact
+      - name: Download artifact
         uses: actions/download-artifact@v4
         with:
           name: dist
